In [1]:
import pandas as pd

In [2]:
fake =pd.read_csv("Fake1.csv")
true=pd.read_csv("True1.csv")
print("done")


done


In [3]:
fake.insert(4,"actual_result","0")
print("done")

done


In [4]:
true.insert(4,"actual_result","1")
print("done")

done


In [5]:
combine=pd.concat([true,fake])

In [6]:
from sklearn.utils import shuffle

In [7]:
combine=shuffle(combine)

In [8]:
combine=shuffle(combine)

In [9]:
 combine.to_csv('shuffled_dataset.csv')

In [11]:
df=pd.read_csv('Shuffled_dataset.csv')

In [13]:
df.head()

Unnamed: 0                                              title  \
0          82  Senate parliamentarian rules against tax bill ...   
1          73   WATCH: Retired Alabama Cop: We Were Told To K...   
2         150  White House says will work with Rubio on child...   
3         117   Trump Seething After Humiliating Virginia Ele...   
4         197  Trump signs into law U.S. government ban on Ka...   

                                                text       subject       date  \
0  WASHINGTON (Reuters) - The U.S. Senate parliam...  politicsNews  19-Dec-17   
1  It seems that Republican candidate for Attorne...          News  22-Nov-17   
2  WASHINGTON (Reuters) - The White House said on...  politicsNews  14-Dec-17   
3  Well, that didn t take long.After weeks of sup...          News   8-Nov-17   
4  WASHINGTON (Reuters) - President Donald Trump ...  politicsNews  12-Dec-17   

   actual_result  
0              1  
1              0  
2              1  
3              0  
4              1

In [14]:
df=df.dropna()

In [16]:
X=df.drop('actual_result',axis=1)

In [19]:
y=df['actual_result']

In [20]:
X.shape

(398, 5)

In [ ]:
y.shape

In [ ]:
!pip install tensorflow

In [18]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import RegexpTokenizer
from nltk.stem import WordNetLemmatizer
from nltk.stem.porter import PorterStemmer
import string
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Ashu\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Ashu\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [19]:
def remove_punctuations(text):
  no_punct= "".join([c for c in text if c not in string.punctuation])
  return no_punct

In [20]:
combine['text']=combine['text'].apply(lambda x: remove_punctuations(x))

In [22]:
combine['text'].tail()

142    WASHINGTON Reuters  Republican governors from ...
102    WASHINGTON Reuters  Republican US Senator Susa...
75     Gene Simmons the 68yearold Kiss bassist and co...
145    AUSTIN TexasWASHINGTON Reuters  US Republican ...
9      Just when you might have thought we d get a br...
Name: text, dtype: object

In [23]:
tokenizer=RegexpTokenizer(r'\w+')

In [24]:
combine['text']=combine['text'].apply(lambda x: tokenizer.tokenize(x.lower()))

In [25]:
combine.text

16     [washington, reuters, a, georgianamerican, bus...
190    [if, you, haven, t, noticed, no, one, associat...
158    [reuters, kentucky, state, representative, dan...
49     [washington, reuters, the, leaders, of, the, u...
131    [this, maniac, wants, the, handmaid, s, tale, ...
                             ...                        
142    [washington, reuters, republican, governors, f...
102    [washington, reuters, republican, us, senator,...
75     [gene, simmons, the, 68yearold, kiss, bassist,...
145    [austin, texaswashington, reuters, us, republi...
9      [just, when, you, might, have, thought, we, d,...
Name: text, Length: 398, dtype: object

In [26]:
def remove_stopwords(text):
  words=[w for w in text if w not in stopwords.words('english')]
  return words

In [27]:
combine['text']=combine['text'].apply(lambda x: remove_stopwords(x))


In [28]:
combine['text']

16     [washington, reuters, georgianamerican, busine...
190    [noticed, one, associated, trump, administrati...
158    [reuters, kentucky, state, representative, dan...
49     [washington, reuters, leaders, us, intelligenc...
131    [maniac, wants, handmaid, tale, become, realit...
                             ...                        
142    [washington, reuters, republican, governors, f...
102    [washington, reuters, republican, us, senator,...
75     [gene, simmons, 68yearold, kiss, bassist, cole...
145    [austin, texaswashington, reuters, us, republi...
9      [might, thought, get, break, watching, people,...
Name: text, Length: 398, dtype: object

In [30]:
lemmatizer=WordNetLemmatizer()
def word_lemmatizer(text):
  lem_text=[lemmatizer.lemmatize(i) for i in text]
  return lem_text 

In [31]:
combine['text'].apply(lambda x: word_lemmatizer(x))


16     [washington, reuters, georgianamerican, busine...
190    [noticed, one, associated, trump, administrati...
158    [reuters, kentucky, state, representative, dan...
49     [washington, reuters, leader, u, intelligence,...
131    [maniac, want, handmaid, tale, become, reality...
                             ...                        
142    [washington, reuters, republican, governor, fo...
102    [washington, reuters, republican, u, senator, ...
75     [gene, simmons, 68yearold, kiss, bassist, cole...
145    [austin, texaswashington, reuters, u, republic...
9      [might, thought, get, break, watching, people,...
Name: text, Length: 398, dtype: object

In [32]:
stemmer= PorterStemmer()

In [33]:
def word_stemmer(text):
  stem_text=" ".join([stemmer.stem(i) for i in text])
  return stem_text

In [34]:
combine['text']=combine['text'].apply(lambda x: word_stemmer(x))


In [35]:
combine['text']

16     washington reuter georgianamerican businessman...
190    notic one associ trump administr includ donald...
158    reuter kentucki state repres dan johnson face ...
49     washington reuter leader us intellig commun th...
131    maniac want handmaid tale becom realityabort p...
                             ...                        
142    washington reuter republican governor four us ...
102    washington reuter republican us senat susan co...
75     gene simmon 68yearold kiss bassist colead sing...
145    austin texaswashington reuter us republican re...
9      might thought get break watch peopl kiss donal...
Name: text, Length: 398, dtype: object

In [36]:
combine.head(10)

title  \
16   U.S. lawmakers question businessman at 2016 Tr...   
190   Melania Trump Hit With SERIOUS Side-Eye After...   
158  Kentucky lawmaker a 'probable suicide' amid se...   
49   Spy chiefs pressure Congress to renew expiring...   
131   WATCH: Republican Lawmaker Claims Forcing Wom...   
197   Trump And John Kelly Just Got RIPPED APART By...   
15    Tone Deaf Trump: Congrats Rep. Scalise On Los...   
42   U.S. court rejects Trump bid to stop transgend...   
192   GOP Senate Candidate Says Kids Were Murdered ...   
97   Trump on Twitter (Dec 18) - Congressional Race...   

                                                  text       subject  \
16   washington reuter georgianamerican businessman...  politicsNews   
190  notic one associ trump administr includ donald...          News   
158  reuter kentucki state repres dan johnson face ...  politicsNews   
49   washington reuter leader us intellig commun th...  politicsNews   
131  maniac want handmaid tale becom realityabort p...          News   
197  donald trump disgrac team deserv throttl horre...          News   
15   donald trump sign gop tax scam law cours meant...          News   
42   new york reuter feder appeal court virginia th...  politicsNews   
192  like christ like christian christian unlik chr...          News   
97   follow statement post verifi twitter account u...  politicsNews   

          date actual_result  
16   27-Dec-17             1  
190  24-Oct-17             0  
158  14-Dec-17             1  
49   21-Dec-17             1  
131   6-Nov-17             0  
197  21-Oct-17             0  
15   20-Dec-17             0  
42   21-Dec-17             1  
192  23-Oct-17             0  
97   18-Dec-17             1

In [38]:
combine

title  \
16   U.S. lawmakers question businessman at 2016 Tr...   
190   Melania Trump Hit With SERIOUS Side-Eye After...   
158  Kentucky lawmaker a 'probable suicide' amid se...   
49   Spy chiefs pressure Congress to renew expiring...   
131   WATCH: Republican Lawmaker Claims Forcing Wom...   
..                                                 ...   
142  Republican governors meet with Pence over NAFT...   
102  Republican Senator Collins says she will vote ...   
75    Fox News Bans Gene Simmons For Life For Haras...   
145  Republican Representative Farenthold will not ...   
9     WATCH: Brand-New Pro-Trump Ad Features So Muc...   

                                                  text       subject  \
16   washington reuter georgianamerican businessman...  politicsNews   
190  notic one associ trump administr includ donald...          News   
158  reuter kentucki state repres dan johnson face ...  politicsNews   
49   washington reuter leader us intellig commun th...  politicsNews   
131  maniac want handmaid tale becom realityabort p...          News   
..                                                 ...           ...   
142  washington reuter republican governor four us ...  politicsNews   
102  washington reuter republican us senat susan co...  politicsNews   
75   gene simmon 68yearold kiss bassist colead sing...          News   
145  austin texaswashington reuter us republican re...  politicsNews   
9    might thought get break watch peopl kiss donal...          News   

          date actual_result  
16   27-Dec-17             1  
190  24-Oct-17             0  
158  14-Dec-17             1  
49   21-Dec-17             1  
131   6-Nov-17             0  
..         ...           ...  
142  14-Dec-17             1  
102  18-Dec-17             1  
75   22-Nov-17             0  
145  14-Dec-17             1  
9    21-Dec-17             0  

[398 rows x 5 columns]

In [39]:
combine.describe()

title  \
count                                                 398   
unique                                                398   
top      Trump Only Cares About Trump; Why He Is Recog...   
freq                                                    1   

                                                     text subject       date  \
count                                                 398     398        398   
unique                                                397       2         71   
top     reuter republican us congress reach deal final...    News  13-Dec-17   
freq                                                    2     199         29   

       actual_result  
count            398  
unique             2  
top                0  
freq             199

In [117]:
y=pd.get_dummies(combine['actual_result'])
y=y.iloc[:,1].values
y

array([1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,

In [118]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=300)
X=cv.fit_transform(combine).toarray()

In [125]:
import numpy as np

In [126]:
def data_split(data,ratio):
    shuffled=np.random.permutation(len(data))
    test_set_size=int(len(data)*ratio)
    test_indices=shuffled[:test_set_size]
    train_indices=shuffled[test_set_size:]
    return data[train_indices],data[test_indices]

In [127]:
train,test=data_split(X,0.4)

In [128]:
train

array([[0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0]], dtype=int64)

In [133]:
test

array([[1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int64)

In [145]:
X_train=train[[X]]
X_test=test[[X]]

D:\anaconda\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  """Entry point for launching an IPython kernel.
D:\anaconda\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  


In [146]:
Y_train=train[[y]]
Y_test=test[[y]]

D:\anaconda\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  """Entry point for launching an IPython kernel.
D:\anaconda\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  


In [ ]:
lr = LogisticRegression()
lr.fit(train_dataset,train_labels)



In [143]:
from sklearn.linear_model import LogisticRegression

In [156]:
nsamples, nx, ny = X_train.shape
dX = X_train.reshape((nsamples,nx*ny))

nsamples, nx, ny = Y_train.shape
d= Y_train.reshape((nsamples,nx*ny))



ValueError: not enough values to unpack (expected 3, got 2)

In [157]:
clf=LogisticRegression()
clf.fit(dX,d)

NameError: name 'd' is not defined